"""Render a faceless text Reel (1080x1920 MP4) from a JSON spec.

Visual style matches the Coach Nas AM Canva posters (ivory #f9f6f0, deep green
#163d32, gold #c9a84c, Cormorant Garamond headlines and italics, green footer bar
with WDT logo and handle, date top-right, mint CTA box with green edge), plus the
motion rules in docs/video-style-rotation.md (gold underline on the key word,
green wipe between scenes).

Background music: an original bed generated by music.py, unless the spec sets
"music" to a path of a licensed track, or to "none".

Usage: python3 render_reel.py spec.json out.mp4
"""
import json
import os
import subprocess
import sys
import tempfile

import imageio_ffmpeg
from PIL import Image, ImageDraw, ImageFont

from music import make_bed

W, H, FPS = 1080, 1920, 30
WIPE = 0.4  # seconds of green wipe at the start of every scene after the first

BG = (249, 246, 240)
GREEN = (22, 61, 50)
BAR = (28, 74, 62)
GOLD = (201, 168, 76)
GOLD_TEXT = (173, 140, 72)
MINT = (232, 240, 237)
IVORY = (248, 245, 238)
SOFT = (77, 107, 96)

HERE = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.join(HERE, "fonts")
HEAD = os.path.join(FONT_DIR, "cormorant-garamond-700-normal.ttf")
ITALIC = os.path.join(FONT_DIR, "cormorant-garamond-600-italic.ttf")
SANS_BOLD = os.path.join(FONT_DIR, "montserrat-700.ttf")
SANS = os.path.join(FONT_DIR, "montserrat-500.ttf")
LOGO = os.path.join(HERE, "assets", "wdt-logo.png")

# Keep text clear of Instagram's Reel UI (top bar, caption/buttons at bottom, right rail).
SAFE_LEFT, SAFE_RIGHT = 90, W - 170
SAFE_TOP, SAFE_BOTTOM = 280, 1400
FOOTER_Y, FOOTER_H = 1450, 120

_fonts = {}


def font(path, size):
    key = (path, size)
    if key not in _fonts:
        _fonts[key] = ImageFont.truetype(path, size)
    return _fonts[key]


def ease(t):
    t = max(0.0, min(1.0, t))
    return 1 - (1 - t) ** 3


def fade(t, start, dur=0.45):
    return ease((t - start) / dur)


def wrap(draw, text, fnt, max_w):
    lines, line = [], ""
    for word in text.split():
        trial = f"{line} {word}".strip()
        if draw.textlength(trial, font=fnt) <= max_w:
            line = trial
        else:
            lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def _norm(word):
    return word.strip(".,!?“”…").upper()


def rich_lines(img, lines, fnt, y, alpha, rise, highlight, t_underline, color=GREEN, spacing=1.15):
    """Draw lines word by word; words in `highlight` get an animated gold underline."""
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    a = int(255 * alpha)
    space = d.textlength(" ", font=fnt)
    hl = {_norm(w) for w in highlight}
    for i, ln in enumerate(lines):
        x, ly = SAFE_LEFT, y + i * fnt.size * spacing + rise
        for word in ln.split():
            wlen = d.textlength(word, font=fnt)
            d.text((x, ly), word, font=fnt, fill=color + (a,))
            if _norm(word) in hl and t_underline > 0:
                uy = ly + fnt.size * 1.0
                d.rectangle([x, uy, x + wlen * ease(t_underline), uy + 8], fill=GOLD + (a,))
            x += wlen + space
    img.alpha_composite(layer)
    return y + len(lines) * fnt.size * spacing


def plain_lines(img, lines, fnt, color, y, alpha, rise, spacing=1.3):
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    for i, ln in enumerate(lines):
        d.text((SAFE_LEFT, y + i * fnt.size * spacing + rise), ln, font=fnt, fill=color + (int(255 * alpha),))
    img.alpha_composite(layer)
    return y + len(lines) * fnt.size * spacing


_base_cache = {}


def base_frame(spec):
    key = id(spec)
    if key not in _base_cache:
        img = Image.new("RGBA", (W, H), BG + (255,))
        d = ImageDraw.Draw(img)
        if spec.get("date_label"):
            f = font(SANS, 34)
            d.text((SAFE_RIGHT - d.textlength(spec["date_label"], font=f), 200), spec["date_label"], font=f, fill=GOLD_TEXT)
        d.rectangle([0, FOOTER_Y, W, FOOTER_Y + FOOTER_H], fill=BAR)
        x = SAFE_LEFT
        if os.path.exists(LOGO):
            logo = Image.open(LOGO).convert("RGBA")
            logo.thumbnail((230, FOOTER_H - 20))
            img.alpha_composite(logo, (x - 60, FOOTER_Y + (FOOTER_H - logo.height) // 2))
            x = x - 60 + logo.width + 30
        f = font(SANS_BOLD, 34)
        d.text((x, FOOTER_Y + (FOOTER_H - 34) // 2 - 4), spec.get("footer", "@coachnas.pharmacist"), font=f, fill=IVORY)
        _base_cache[key] = img
    return _base_cache[key].copy()


def render_scene(spec, scene, t):
    img = base_frame(spec)
    d = ImageDraw.Draw(img)
    max_w = SAFE_RIGHT - SAFE_LEFT
    kind = scene["type"]
    hl = scene.get("highlight", [])

    if kind == "hook":
        hf = font(HEAD, 128)
        lines = wrap(d, scene["text"], hf, max_w)
        y = SAFE_TOP + 120
        if scene.get("kicker"):
            a = fade(t, 0.0)
            y = plain_lines(img, [scene["kicker"].upper()], font(SANS_BOLD, 34), GOLD_TEXT, y, a, (1 - a) * 30) + 40
        a = fade(t, 0.2, 0.55)
        y = rich_lines(img, lines, hf, y, a, (1 - a) * 50, hl, (t - 0.9) / 0.5) + 30
        a3 = fade(t, 0.9)
        d.rectangle([SAFE_LEFT, y, SAFE_LEFT + int(90 * a3), y + 4], fill=GOLD)
        if scene.get("sub"):
            a2 = fade(t, 1.1)
            sf = font(ITALIC, 60)
            plain_lines(img, wrap(d, scene["sub"], sf, max_w), sf, GREEN, y + 50, a2, (1 - a2) * 30)

    elif kind == "steps":
        y = SAFE_TOP + 100
        tf = font(ITALIC, 64)
        a = fade(t, 0.0)
        y = plain_lines(img, wrap(d, scene["title"], tf, max_w), tf, GREEN, y, a, (1 - a) * 30) + 60
        nf = font(HEAD, 66)
        sf = font(HEAD, scene.get("step_size", 76))
        notef = font(ITALIC, 44)
        gap = scene.get("step_gap", 0.8)
        notes = scene.get("notes", [])
        row_h = 270 if notes else 180
        text_w = SAFE_RIGHT - SAFE_LEFT - 150
        for i, step in enumerate(scene["steps"]):
            a = fade(t, 0.4 + i * gap)
            if a <= 0:
                continue
            layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
            ld = ImageDraw.Draw(layer)
            cy, off, al = y + i * row_h, (1 - a) * 60, int(255 * a)
            last = i == len(scene["steps"]) - 1
            ld.ellipse([SAFE_LEFT + off, cy, SAFE_LEFT + 110 + off, cy + 110], fill=(GOLD if last else GREEN) + (al,))
            num = str(i + 1)
            ld.text((SAFE_LEFT + 55 + off - ld.textlength(num, font=nf) / 2, cy + 12), num, font=nf, fill=IVORY + (al,))
            ld.text((SAFE_LEFT + 150 + off, cy + 14), step.upper(), font=sf, fill=GREEN + (al,))
            if i < len(notes) and notes[i]:
                for j, ln in enumerate(wrap(ld, notes[i], notef, text_w)):
                    ld.text((SAFE_LEFT + 150 + off, cy + 110 + j * 52), ln, font=notef, fill=SOFT + (al,))
            img.alpha_composite(layer)

    elif kind == "statement":
        bf = font(HEAD, 104)
        lines = wrap(d, scene["text"], bf, max_w)
        sf = font(ITALIC, 60)
        sub = wrap(d, scene["sub"], sf, max_w) if scene.get("sub") else []
        block_h = len(lines) * bf.size * 1.15 + (50 + len(sub) * sf.size * 1.3 if sub else 0)
        y = (SAFE_TOP + SAFE_BOTTOM) / 2 - block_h / 2
        a = fade(t, 0.0, 0.6)
        y = rich_lines(img, lines, bf, y, a, (1 - a) * 40, hl, (t - 0.7) / 0.5) + 50
        if sub:
            a2 = fade(t, 0.8)
            plain_lines(img, sub, sf, SOFT, y, a2, (1 - a2) * 30)

    elif kind == "cta":
        cf = font(HEAD, 84)
        lines = wrap(d, scene["text"].upper(), cf, max_w - 80)
        box_h = len(lines) * cf.size * 1.15 + 90
        y = (SAFE_TOP + SAFE_BOTTOM) / 2 - box_h / 2 - 60
        a = fade(t, 0.0)
        al = int(255 * a)
        layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
        ld = ImageDraw.Draw(layer)
        ld.rectangle([SAFE_LEFT - 30, y, W - 60, y + box_h], fill=MINT + (al,))
        ld.rectangle([SAFE_LEFT - 30, y, SAFE_LEFT - 24, y + box_h], fill=BAR + (al,))
        img.alpha_composite(layer)
        yy = y + 45
        for ln in lines:
            layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
            ImageDraw.Draw(layer).text((SAFE_LEFT + 20, yy + (1 - a) * 20), ln, font=cf, fill=GOLD_TEXT + (al,))
            img.alpha_composite(layer)
            yy += cf.size * 1.15
        if scene.get("sub"):
            a2 = fade(t, 0.6)
            sf = font(ITALIC, 60)
            plain_lines(img, wrap(d, scene["sub"], sf, max_w), sf, GREEN, y + box_h + 50, a2, (1 - a2) * 30)

    return img


def apply_wipe(img, t):
    """Deep-green panel sweeps left to right, revealing the new scene."""
    if t >= WIPE:
        return img
    p = t / WIPE
    lead = int(W * ease(min(1, p * 1.6)))
    trail = int(W * ease(max(0, p * 1.6 - 0.6)))
    if lead > trail:
        ImageDraw.Draw(img).rectangle([trail, 0, lead, H], fill=BAR)
    return img


def main(spec_path, out_path):
    with open(spec_path, encoding="utf-8") as fh:
        spec = json.load(fh)
    seconds = sum(s["duration"] for s in spec["scenes"])

    music = spec.get("music", "auto")
    tmp_wav = None
    if music == "auto":
        tmp_wav = tempfile.NamedTemporaryFile(suffix=".wav", delete=False).name
        make_bed(seconds, tmp_wav, seed=sum(map(ord, spec.get("date", ""))))
        audio_in = ["-i", tmp_wav]
    elif music and music != "none":
        audio_in = ["-stream_loop", "-1", "-i", os.path.join(os.path.dirname(spec_path), music)]
    else:
        audio_in = ["-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo"]

    fade_out = max(0.0, seconds - 1.5)
    cmd = [
        imageio_ffmpeg.get_ffmpeg_exe(), "-y", "-loglevel", "error",
        "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{W}x{H}", "-r", str(FPS), "-i", "-",
        *audio_in,
        "-af", f"afade=t=in:d=0.8,afade=t=out:st={fade_out}:d=1.5",
        "-t", str(seconds), "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "medium", "-crf", "20",
        "-c:a", "aac", "-b:a", "160k", "-movflags", "+faststart", out_path,
    ]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE)
    for n, scene in enumerate(spec["scenes"]):
        for f in range(int(scene["duration"] * FPS)):
            t = f / FPS
            img = render_scene(spec, scene, t)
            if n > 0:
                img = apply_wipe(img, t)
            proc.stdin.write(img.convert("RGB").tobytes())
    proc.stdin.close()
    code = proc.wait()
    if tmp_wav:
        os.unlink(tmp_wav)
    if code != 0:
        sys.exit("ffmpeg failed")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
